import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform, Alert } from 'react-native';

export async function generateLegalReport(result: any, madhab: string) {
  const today = new Date().toLocaleDateString('ar-EG', { year: 'numeric', month: 'long', day: 'numeric' });
  const html = `
  <html>
  <head>
    <style>
      body { font-family: 'Arial', sans-serif; padding: 30px; }
      .header { text-align: center; border-bottom: 2px solid #0D7C66; padding-bottom: 10px; margin-bottom: 20px; }
      .title { font-size: 22px; font-weight: bold; color: #0D7C66; }
      .subtitle { font-size: 14px; color: #666; }
      .section { margin-bottom: 20px; }
      .table { width: 100%; border-collapse: collapse; }
      .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
      .table th { background-color: #0D7C66; color: white; }
      .signature { margin-top: 40px; border-top: 1px solid #000; padding-top: 10px; font-size: 12px; text-align: center; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="title">Inheritance Distribution Report</div>
      <div class="subtitle">According to ${madhab} school – ${today}</div>
    </div>
    <div class="section">
      <h3>Estate Summary</h3>
      <p>Net Estate: $${result.netEstate || result.netTotal}</p>
    </div>
    <div class="section">
      <h3>Heir Distribution</h3>
      <table class="table">
        <tr><th>Heir</th><th>Amount</th><th>Fraction</th></tr>
        ${result.shares.map((s: any) => `<tr><td>${s.name}</td><td>$${s.amount.toFixed(2)}</td><td>${s.fraction.numerator}/${s.fraction.denominator}</td></tr>`).join('')}
      </table>
    </div>
    <div class="signature">
      <p>Generated by Merath App</p>
      <p>This report is for reference purposes only. For legal advice, consult a qualified scholar.</p>
    </div>
  </body>
  </html>`;
  const { uri } = await Print.printToFileAsync({ html });
  if (Platform.OS === 'android') {
    await Sharing.shareAsync(uri);
  } else {
    Alert.alert('Report Saved', `Legal report saved to ${uri}`);
  }
}
